/**
 * CoursewareComicStoryboardWorkspaceStyles.ts
 *
 * 第二步单任务分镜工作台的展示常量。
 * 样式与交互逻辑分离，避免主组件再次接近900行。
 */

import type { CSSProperties } from 'react'

export const storyboardColors = {
  primary: '#7C3AED',
  primaryDark: '#6D28D9',
  success: '#059669',
  warning: '#D97706',
  danger: '#DC2626',
  text: '#172033',
  textSecondary: '#5B667A',
  textMuted: '#8A94A7',
  border: '#E4E8F0',
  background: '#F6F7FB',
  white: '#FFFFFF',
}

export const storyboardStyles: Record<string, CSSProperties> = {
  container: { marginBottom: 14 },
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  title: {
    margin: 0,
    color: storyboardColors.text,
    fontSize: 18,
    fontWeight: 900,
    lineHeight: 1.35,
  },
  description: {
    marginTop: 4,
    color: storyboardColors.textSecondary,
    fontSize: 13,
    lineHeight: 1.55,
  },
  headerBadges: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    flexWrap: 'wrap',
  },
  badge: {
    padding: '6px 9px',
    borderRadius: 999,
    background: '#F5F3FF',
    color: storyboardColors.primaryDark,
    fontSize: 12,
    fontWeight: 800,
  },
  mutedBadge: {
    padding: '6px 9px',
    borderRadius: 999,
    background: storyboardColors.background,
    color: storyboardColors.textSecondary,
    fontSize: 12,
    fontWeight: 800,
  },
  reviewBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    padding: '9px 12px',
    borderRadius: 11,
    border: `1px solid ${storyboardColors.border}`,
    background: storyboardColors.background,
    color: storyboardColors.textSecondary,
    fontSize: 13,
    lineHeight: 1.5,
  },
  warningBar: {
    marginBottom: 12,
    padding: '9px 12px',
    borderRadius: 11,
    border: '1px solid #FDE68A',
    background: '#FFFBEB',
    color: '#92400E',
    fontSize: 13,
    lineHeight: 1.5,
  },
  workspace: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 14,
    flexWrap: 'wrap',
  },
  navigator: {
    minWidth: 190,
    flex: '0 1 220px',
    overflow: 'hidden',
    borderRadius: 15,
    border: `1px solid ${storyboardColors.border}`,
    background: storyboardColors.white,
  },
  navigatorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '12px 13px',
    borderBottom: `1px solid ${storyboardColors.border}`,
  },
  navigatorTitle: {
    color: storyboardColors.text,
    fontSize: 14,
    fontWeight: 900,
  },
  navigatorCount: {
    color: storyboardColors.textMuted,
    fontSize: 12,
  },
  navigatorList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    maxHeight: 620,
    padding: 8,
    overflowY: 'auto',
  },
  navigatorButton: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    gap: 9,
    minHeight: 54,
    padding: '9px 10px',
    borderRadius: 11,
    border: '1px solid',
    fontFamily: 'inherit',
    textAlign: 'left',
  },
  navigatorNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    flexShrink: 0,
    borderRadius: 9,
    fontSize: 12,
    fontWeight: 900,
  },
  navigatorText: { minWidth: 0, flex: 1 },
  navigatorPurpose: {
    display: 'block',
    overflow: 'hidden',
    color: storyboardColors.text,
    fontSize: 13,
    fontWeight: 800,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  navigatorStatus: {
    display: 'block',
    marginTop: 3,
    color: storyboardColors.textMuted,
    fontSize: 11,
  },
  dirtyDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
    borderRadius: 999,
    background: storyboardColors.warning,
  },
  editor: {
    minWidth: 320,
    flex: '2 1 500px',
    overflow: 'hidden',
    borderRadius: 15,
    border: `1px solid ${storyboardColors.border}`,
    background: storyboardColors.white,
    boxShadow: '0 12px 34px rgba(15,23,42,0.06)',
  },
  editorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '14px 16px',
    borderBottom: `1px solid ${storyboardColors.border}`,
    flexWrap: 'wrap',
  },
  editorTitleRow: {
    display: 'flex',
    alignItems: 'center',
    minWidth: 0,
    gap: 10,
  },
  editorNumber: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 34,
    height: 34,
    flexShrink: 0,
    borderRadius: 11,
    background: 'linear-gradient(135deg,#7C3AED,#4F46E5)',
    color: storyboardColors.white,
    fontSize: 14,
    fontWeight: 900,
  },
  editorTitle: {
    color: storyboardColors.text,
    fontSize: 16,
    fontWeight: 900,
  },
  editorStatus: {
    marginTop: 2,
    color: storyboardColors.textMuted,
    fontSize: 12,
  },
  editorBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 14,
    padding: 16,
  },
  section: {
    padding: 13,
    borderRadius: 12,
    background: storyboardColors.background,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 10,
  },
  sectionTitle: {
    color: storyboardColors.text,
    fontSize: 14,
    fontWeight: 900,
  },
  sectionHint: {
    color: storyboardColors.textMuted,
    fontSize: 11,
  },
  fieldGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))',
    gap: 10,
  },
  field: { display: 'block', minWidth: 0 },
  fieldLabelRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 5,
  },
  fieldLabel: {
    color: storyboardColors.textSecondary,
    fontSize: 13,
    fontWeight: 800,
  },
  fieldCounter: {
    color: storyboardColors.textMuted,
    fontSize: 11,
  },
  fieldInput: {
    width: '100%',
    minHeight: 92,
    boxSizing: 'border-box',
    resize: 'vertical',
    padding: '10px 11px',
    borderRadius: 10,
    border: `1px solid ${storyboardColors.border}`,
    background: storyboardColors.white,
    color: storyboardColors.text,
    fontFamily: 'inherit',
    fontSize: 14,
    lineHeight: 1.55,
    outline: 'none',
  },
  compactInput: { minHeight: 72 },
  knowledgeInput: {
    border: '1px solid #C4B5FD',
    background: '#FCFAFF',
  },
  details: {
    borderRadius: 12,
    border: `1px solid ${storyboardColors.border}`,
    background: storyboardColors.white,
  },
  detailsSummary: {
    padding: '11px 13px',
    color: storyboardColors.textSecondary,
    fontSize: 13,
    fontWeight: 800,
    cursor: 'pointer',
  },
  detailsBody: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))',
    gap: 10,
    padding: '0 13px 13px',
  },
  textSummary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: '10px 12px',
    borderRadius: 10,
    background: storyboardColors.white,
    color: storyboardColors.textSecondary,
    fontSize: 13,
  },
  textSummaryValue: {
    overflow: 'hidden',
    color: storyboardColors.textMuted,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  fieldError: {
    padding: '9px 11px',
    borderRadius: 10,
    background: '#FEF2F2',
    color: storyboardColors.danger,
    fontSize: 12,
    lineHeight: 1.5,
  },
  actionBar: {
    position: 'sticky',
    bottom: 0,
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: '11px 14px',
    borderTop: `1px solid ${storyboardColors.border}`,
    background: 'rgba(255,255,255,0.96)',
    boxShadow: '0 -8px 24px rgba(15,23,42,0.05)',
    backdropFilter: 'blur(8px)',
    flexWrap: 'wrap',
  },
  actionGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  actionHint: {
    color: storyboardColors.textMuted,
    fontSize: 12,
  },
  secondaryButton: {
    minHeight: 40,
    padding: '9px 13px',
    borderRadius: 10,
    border: `1px solid ${storyboardColors.border}`,
    background: storyboardColors.white,
    color: storyboardColors.textSecondary,
    fontSize: 13,
    fontWeight: 800,
    cursor: 'pointer',
  },
  primaryButton: {
    minHeight: 42,
    padding: '10px 16px',
    borderRadius: 11,
    border: 'none',
    background: 'linear-gradient(135deg,#7C3AED,#4F46E5)',
    color: storyboardColors.white,
    fontSize: 14,
    fontWeight: 900,
    cursor: 'pointer',
  },
  assistant: {
    minWidth: 250,
    flex: '1 1 280px',
    overflow: 'hidden',
    borderRadius: 15,
    border: '1px solid #DDD6FE',
    background: '#FCFAFF',
  },
  assistantCollapsed: {
    width: '100%',
    padding: 15,
    border: 'none',
    background: 'transparent',
    color: storyboardColors.primaryDark,
    textAlign: 'left',
    cursor: 'pointer',
  },
  assistantCollapsedTitle: {
    fontSize: 14,
    fontWeight: 900,
  },
  assistantCollapsedHint: {
    marginTop: 4,
    color: storyboardColors.textSecondary,
    fontSize: 12,
    lineHeight: 1.5,
  },
  assistantHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '12px 13px',
    borderBottom: '1px solid #EDE9FE',
  },
  assistantTitle: {
    color: storyboardColors.primaryDark,
    fontSize: 14,
    fontWeight: 900,
  },
  assistantClose: {
    width: 30,
    height: 30,
    borderRadius: 9,
    border: '1px solid #DDD6FE',
    background: storyboardColors.white,
    color: storyboardColors.textSecondary,
    fontSize: 16,
    cursor: 'pointer',
  },
  assistantBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 13,
  },
  quickTitle: {
    color: storyboardColors.textSecondary,
    fontSize: 12,
    fontWeight: 800,
  },
  quickGrid: { display: 'flex', gap: 7, flexWrap: 'wrap' },
  quickButton: {
    padding: '7px 9px',
    borderRadius: 999,
    border: '1px solid #DDD6FE',
    background: storyboardColors.white,
    color: storyboardColors.primaryDark,
    fontSize: 12,
    fontWeight: 700,
    cursor: 'pointer',
  },
  select: {
    width: '100%',
    minHeight: 40,
    padding: '9px 10px',
    borderRadius: 10,
    border: '1px solid #DDD6FE',
    background: storyboardColors.white,
    color: storyboardColors.text,
    fontFamily: 'inherit',
    fontSize: 13,
    outline: 'none',
  },
  assistantInput: {
    width: '100%',
    minHeight: 120,
    boxSizing: 'border-box',
    resize: 'vertical',
    padding: '10px 11px',
    borderRadius: 10,
    border: '1px solid #DDD6FE',
    background: storyboardColors.white,
    color: storyboardColors.text,
    fontFamily: 'inherit',
    fontSize: 13,
    lineHeight: 1.55,
    outline: 'none',
  },
  assistantCounter: {
    color: storyboardColors.warning,
    fontSize: 11,
    textAlign: 'right',
  },
  assistantButton: {
    minHeight: 40,
    padding: '9px 12px',
    borderRadius: 10,
    border: 'none',
    background: 'linear-gradient(135deg,#D97706,#EA580C)',
    color: storyboardColors.white,
    fontSize: 13,
    fontWeight: 900,
    cursor: 'pointer',
  },
}
